- name: SSH and deploy
  uses: appleboy/ssh-action@v0.1.10
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ubuntu
    key: ${{ secrets.EC2_DEPLOY }}
    script: |
      # 개인 키 저장
      echo "${{ secrets.EC2_DEPLOY }}" > ~/.ssh/deploy-key
      chmod 600 ~/.ssh/deploy-key

      # git clone (SSH 방식)
      if [ ! -d "quant-frontend" ]; then
        GIT_SSH_COMMAND="ssh -i ~/.ssh/deploy-key -o StrictHostKeyChecking=no" \
        git clone git@github.com:GiHoon1123/quant-frontend.git
      fi

      cd quant-frontend
      GIT_SSH_COMMAND="ssh -i ~/.ssh/deploy-key -o StrictHostKeyChecking=no" \
      git pull origin main

      npm install
      npm run build

      # 기존 실행 중이면 종료
      pkill -f "next start" || true

      # 백그라운드 실행
      nohup npm run start > out.log 2>&1 &
