name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_DEPLOY_PRIVATE_KEY }}
          script: |
            # 개인 키 저장
            echo "${{ secrets.EC2_DEPLOY_PRIVATE_KEY }}" > ~/.ssh/deploy-key
            chmod 600 ~/.ssh/deploy-key

            # git clone (SSH 방식)
            if [ ! -d "quant-frontend" ]; then
              GIT_SSH_COMMAND="ssh -i ~/.ssh/deploy-key -o StrictHostKeyChecking=no" \
              git clone git@github.com:GiHoon1123/quant-frontend.git
            fi

            cd quant-frontend
            GIT_SSH_COMMAND="ssh -i ~/.ssh/deploy-key -o StrictHostKeyChecking=no" \
            git pull origin main

            npm install
            npm run build

            pkill -f "next start" || true
            nohup npm run start > out.log 2>&1 &

            sleep 10
